# Whole Genome methylation Association Analysis for Allergic Asthma (AA):  Aim 1


## Summary 

Updates on the analysis results with corrected pvalues. 


## Data 

Phenotype and genotype of interests:

* AA only versus control (neither AA nor AD)

* Methylation profile (methylation proportions at each CpG; after arc-sin square root transformation) from  Illumina 450k microarray.

Other Covariates:

* age at recruitment (AgeCalc)
* sex
* smoking status. Non-smoker versus smoker (current or former).
* Five surrogate variables (SVs) to capture hidden sources of variation in the methylation data. sv1, …sv5.
* Cell-type proportions.
* Random Effect: Family ID (FID) was included as a random effect to account for shared genetic and environmental factors within families.


## Models 


### Model 1

* Y: AA Status (0/1)

* X: arc-sin square root transformed methylation beta values at each CpG. 

* Other covariates as fixed effects.

* Family ID (FID) as random effect.

* algorithm: 
  - stage 1: feature selection using glmmLASSO with logit link.
  - stage 2: linear mixed effect model with the glmmLASSO selected features from stage 1 with logit link. Collect the final pvalue for the selected features.

### Model 2

* Y: arc-sin square root transformed methylation beta values at each CpG. 

* X: AA Status (0/1)  

* Other covariates as fixed effects.

* Family ID (FID) as random effect.

* algorithm: linear mixed effect model.

### Model 3

* Y: arc-sin square root transformed methylation beta values at each CpG. 

* X: AA Status (0/1) 

* Other covariates as fixed effects.

* Family ID (FID) as random effect.

* algorithm: 
  - stage 1: feature selection using glmmLASSO.
  - stage 2: linear mixed effect model with the glmmLASSO selected features from stage 1. Collect the final pvalue for the selected features.

## Results 


### Manhattan Plots

We demonstrate the Manhattan plots of methylation association pvalues from Model 1-3. The x-axis is the genomic position of each CpG site, and the y-axis is the -log10(p-value) of the association between methylation and AA status. The horizental line indicates the genome-wide significance threshold (5e-8 and 1e-5). 

In summary: 

* Model 1 have 70 CpGs with pvalue < 1e-5.
* Model 2 have 90 CpGs with pvalue < 1e-5.
* Model 3 have 5 CpGs with pvalue < 1e-5.



![Figure 1. Manhattan plot for pvalues from model 1. ](M1_manhattan.jpg)

![Figure 2. Manhattan plot for pvalues from model 2. ](M2_manhattan.jpg)

![Figure 3. Manhattan plot for pvalues from model 3. ](M3_manhattan.jpg)

## Agreement between models


Vendiagram of the signifcant CpGs from model 1 and model 2 under threshold pvalue < 1e-5.

![Figure 4. Vendiagram of significant CpGs from Model 1 and Model 2 under threshold pvalue < 1e-5. ](venn_123.jpeg)


## Annotated genes 



### Model 1: 



70 CpGs with pvalue < 1e-5.

In [8]:
import pandas as pd

# 1) load your CSV into a DataFrame
df = pd.read_csv("M1_genes.csv")

# 2) just put `df` as the last line in a cell to get the pretty notebook table
df

             SYMBOL     ENTREZID
0            EMX2OS     196047.0
1              EMX2       2018.0
2             PTPRE       5791.0
3         MIR1915HG     399726.0
4          MARVELD1      83742.0
5            GOLGA3       2802.0
6              ATN1       1822.0
7             RASA3      22821.0
8           TMEM179     388021.0
9               NaN          NaN
10            ACOT2      10965.0
11            HERC2       8924.0
12          CASKIN1      57524.0
13           CACNG3      10368.0
14         CCDC102A      92922.0
15            FBXL8      55336.0
16            TUBB3      10381.0
17            CRHR1       1394.0
18  LINC02210-CRHR1  104909134.0
19         TOB1-AS1     400604.0
20             SKA2     348235.0
21          SEPTIN9      10801.0
22            SIRT6      51548.0
23         C1orf127     148345.0
24            PROX1       5629.0
25            TAF5L      27097.0
26           RNF19B     127544.0
27             LRP8       7804.0
28           CELSR1       9620.0
29            RGPD5      84220.0
30            RGPD8     727851.0
31           TMEM44      93109.0
32            UQCC5     440957.0
33            PBRM1      55193.0
34            TNIP3      79931.0
35         TMEM184C      55751.0
36           GABRG1       2565.0
37            GFOD1      54438.0
38            VARS1       7407.0
39        LINC01564  101927171.0
40             MEST       4232.0
41          DYNC2I1      55112.0
42           MAD1L1       8379.0
43             ACTB         60.0
44             LY6H       4062.0
45           SH2D4A      63898.0
46         EPB41L4B      54566.0
47          COL27A1      85301.0
48           UAP1L1      91373.0
49            SPIN1      10927.0

* PTPRE

The second strongest signal.

Also found in Karine Tremblay and Catherine Laprise's paper "Genes to Diseases (G2D) Computational Method to Identify Asthma Candidate Genes" found rs7081735 in PTPRE associated with childhood allergic asthma in SLSJ cohort.

Note that the strongest signal is in the gene TMEM184C, which may play role in the cell growth and membrane protein coding, but not directly related to asthma.


* CRHR1 

Multiple studies found that CRHR1 variants modulate inhaled corticosteroid (ICS) response in asthma (e.g. rs1876828 and rs242941). 


* VARS1

A very strong signal in the analysis. 

Located in HLA/MHC region, found associated with Neurodevelopmental Disorder With Microcephaly, Seizures, And Cortical Atrophy. But not direct evidence linking to asthma in existing studies.

We conducted

* functional enrichment analysis using the significant CpGs. The result did not yield interesting functional terms direclty related to asthma. 

* Pre-ranked gene set enrichment analysis (GSEA) for the Asthma pathway.  The analysis concluded that the asthma pathway (hsa05310) is not enriched in the association results.

### Model 2: 



90 CpGs with pvalue < 1e-5.

In [9]:
import pandas as pd

# 1) load your CSV into a DataFrame
df = pd.read_csv("M2_genes.csv")

# 2) just put `df` as the last line in a cell to get the pretty notebook table
df

             SYMBOL     ENTREZID
0            EMX2OS     196047.0
1              EMX2       2018.0
2            SH2D4B     387694.0
3          MARVELD1      83742.0
4               NaN          NaN
5            EIF4G2       1982.0
6             TECTA       7007.0
7       TBCEL-TECTA  116804918.0
8            MRPL23       6150.0
9           PACSIN3      29763.0
10           GOLGA3       2802.0
11           TUBA1C      84790.0
12           ATP11A      23250.0
13          TMEM179     388021.0
14            PACS2      23241.0
15             NDE1      54820.0
16            MYH11       4629.0
17         CCDC102A      92922.0
18     LOC101928475  101928475.0
19             PEMT      10400.0
20          RTN4RL1     146760.0
21            CRHR1       1394.0
22  LINC02210-CRHR1  104909134.0
23         TOB1-AS1     400604.0
24          GABARAP      11337.0
25         C19orf25     148223.0
26           CYP2A7       1549.0
27           ZNF235       9310.0
28           NMNAT1      64802.0
29           PRDM16      63976.0
30         PPP1R16B      26051.0
31            NCOA5      57727.0
32           PRDM15      63977.0
33           CELSR1       9620.0
34             OTX1       5013.0
35            SIAH2       6478.0
36          SALL4P5  100130785.0
37          SLC6A20      54716.0
38           EIF4E3     317649.0
39            ALPK1      80216.0
40           CYP4V2     285440.0
41           CTNND2       1501.0
42         CDC42SE2      56990.0
43          MTHFD1L      25902.0
44            DCDC2      51473.0
45            KAAG1     353219.0
46            EXOC2      55770.0
47            DPPA5     340168.0
48             MEST       4232.0
49            CALD1        800.0
50          TSPAN13      27075.0
51             PSD3      23362.0
52           SH2D4A      63898.0
53           BNIP3L        665.0
54            INTS9      55756.0
55         FAM86B3P     286042.0
56         EPB41L4B      54566.0
57            RNF38     152006.0
58              AUH        549.0

None of these genes are really interesting, except CRHR1, which was a hit for model 1.

## Model 3:


5 CpGs with pvalue < 1e-5.

In [10]:
import pandas as pd

# 1) load your CSV into a DataFrame
df = pd.read_csv("M3_genes.csv")

# 2) just put `df` as the last line in a cell to get the pretty notebook table
df

    SYMBOL  ENTREZID
0  PACSIN3     29763
1    MARK4     57787
2    NKPD1    284353
3   ZNF831    128611
4    CNOT9      9125
5   SH2D4A     63898

No interesting genes.



### Conclusion


As a whole, univaraite assoication analysis between each CpG and allergic asthma status can inflate false positives (as a lone outlier drives the hit). This could explain some of the extreme low pvalues from model 1 and model 2, of which sometimes are due to perfect seperation between AA/control groups on odd CpGs. As a rsult, these scattered hits across the genome also make pathway enrichment analysis under-powered.

The single CpG analysis could also dilute true signals (if each individual site’s effect is small) by penalizing the pvalues too much.

## Next Steps

Move to region-level tests such as SOMNiBUS.

This will boost power by aggregating small and coordinated sginals across region, if there are any.